# Generated by Django 5.0.2 on 2024-03-24 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_pub', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='manga_images/')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_emi', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='manga_images/')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_pub', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('consola', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='manga_images/')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.perfil')),
            ],
        ),
    ]
