# Generated by Django 5.0.2 on 2024-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/manga_images/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images/'),
        ),
    ]
