# Generated by Django 5.0.2 on 2024-03-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_anime_img_alter_manga_img_alter_perfil_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='subido_por',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='subido_por',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='subido_por',
        ),
    ]
